/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.imageio.*;
import java.awt.image.*;
import javax.swing.table.DefaultTableModel;

/**
 * Hangman game GUI.
 * @author Cecil Bowen/Will McMurran
 */
public class HangmanMainGUI extends javax.swing.JFrame {

    /**
     * Creates new form HangmanMainGUI
     */
    public HangmanMainGUI() {
        this.nooseURL = "resources/images/noose.png";
        this.headURL = "resources/images/head.png";
        this.bodyURL = "resources/images/body.png";
        this.legsURL = "resources/images/legs.png";
        this.armsURL = "resources/images/arms.png";
        this.eyesURL = "resources/images/eyes.png";
        this.mouthURL = "resources/images/mouth.png";
        initComponents();
    }
    
    Hangman game = new Hangman();
    
    //Setting up image vars
    public Color hangmanColor = Color.black;
    HangmanPreferencesGUI prefLoader = new HangmanPreferencesGUI(this); //only created to load preferences the first time
    
    private BufferedImage imageNoose;
    private BufferedImage imageHead;
    private BufferedImage imageBody;
    private BufferedImage imageLegs;
    private BufferedImage imageArms;
    private BufferedImage imageEyes;
    private BufferedImage imageMouth;
    
    private final String nooseURL;
    private final String headURL;
    private final String bodyURL;
    private final String legsURL;
    private final String armsURL;
    private final String eyesURL;
    private final String mouthURL;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDifficulty = new javax.swing.ButtonGroup();
        jPanelTitle = new javax.swing.JPanel();
        jButtonStartGame = new javax.swing.JButton();
        jButtonDictionary = new javax.swing.JButton();
        jRadioButtonEasy = new javax.swing.JRadioButton();
        jRadioButtonNormal = new javax.swing.JRadioButton();
        jRadioButtonHard = new javax.swing.JRadioButton();
        jLabelTitleText = new javax.swing.JLabel();
        jButtonPreferences1 = new javax.swing.JButton();
        jRadioButtonAny = new javax.swing.JRadioButton();
        jPanelDictionary = new javax.swing.JPanel();
        jComboBoxSelectList = new javax.swing.JComboBox<>();
        jTextFieldAddWord = new javax.swing.JTextField();
        jButtonAddWord = new javax.swing.JButton();
        jButtonRemoveWord = new javax.swing.JButton();
        jButtonDeleteList = new javax.swing.JButton();
        jScrollPaneWords = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanelCreateNewList = new javax.swing.JPanel();
        jLabelListName = new javax.swing.JLabel();
        jTextFieldAddList = new javax.swing.JTextField();
        jButtonBuildList = new javax.swing.JButton();
        jLabelHangmanDictionary = new javax.swing.JLabel();
        jButtonPreferences3 = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jPanelGame = new javax.swing.JPanel();
        jPanelHangmanGraphics = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imageNoose, 0, 0, null);
                if (game.getMissesUsed() >= 1) g.drawImage(dye(imageHead, hangmanColor), 0, 0, null);
                if (game.getMissesUsed() >= 2) g.drawImage(dye(imageBody, hangmanColor), 0, 0, null);
                if (game.getMissesUsed() >= 3) g.drawImage(dye(imageLegs, hangmanColor), 0, 0, null);
                if (game.getMissesUsed() >= 4) g.drawImage(dye(imageArms, hangmanColor), 0, 0, null);
                if (game.getMissesUsed() >= 5) g.drawImage(dye(imageEyes, hangmanColor), 0, 0, null);
                if (game.getMissesUsed() >= 6) g.drawImage(dye(imageMouth, hangmanColor), 0, 0, null);
            }
        };
        jButtonPreferences2 = new javax.swing.JButton();
        jLabelResult = new javax.swing.JLabel();
        jLabelScore = new javax.swing.JLabel();
        jPanelAlphabet = new javax.swing.JPanel();
        jButtonA = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();
        jButtonG = new javax.swing.JButton();
        jButtonH = new javax.swing.JButton();
        jButtonI = new javax.swing.JButton();
        jButtonJ = new javax.swing.JButton();
        jButtonK = new javax.swing.JButton();
        jButtonL = new javax.swing.JButton();
        jButtonM = new javax.swing.JButton();
        jButtonN = new javax.swing.JButton();
        jButtonO = new javax.swing.JButton();
        jButtonP = new javax.swing.JButton();
        jButtonQ = new javax.swing.JButton();
        jButtonR = new javax.swing.JButton();
        jButtonS = new javax.swing.JButton();
        jButtonT = new javax.swing.JButton();
        jButtonU = new javax.swing.JButton();
        jButtonV = new javax.swing.JButton();
        jButtonW = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jButtonZ = new javax.swing.JButton();
        jScrollPaneWord = new javax.swing.JScrollPane();
        jLabelWord = new javax.swing.JLabel();
        jButtonQuit = new javax.swing.JButton();
        jButtonContinue = new javax.swing.JButton();
        jPanelLeaderboard = new javax.swing.JPanel();
        jScrollPaneLeaderboard = new javax.swing.JScrollPane();
        jTableLeaderboard = new javax.swing.JTable(new DefaultTableModel(game.getScores(),new String[]{"Name","Score"}));
        jButtonLeaderboardOkay = new javax.swing.JButton();
        jPanelLeaderboardInput = new javax.swing.JPanel();
        jTextLeaderboardInputName = new javax.swing.JTextField();
        jLabelLeaderboardInputName = new javax.swing.JLabel();
        jButtonLeaderboardInputConfirm = new javax.swing.JButton();
        jLabelLeaderboardInputCongrats = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelTitle.setName("cardTitle"); // NOI18N

        jButtonStartGame.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonStartGame.setText("Start Game");
        jButtonStartGame.setName("jButton_StartGame"); // NOI18N
        jButtonStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartGameActionPerformed(evt);
            }
        });

        jButtonDictionary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDictionary.setText("Dictionary");
        jButtonDictionary.setName("jButton_Dictionary"); // NOI18N
        jButtonDictionary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDictionaryActionPerformed(evt);
            }
        });

        buttonGroupDifficulty.add(jRadioButtonEasy);
        jRadioButtonEasy.setText("Easy");
        jRadioButtonEasy.setName("jRadioButton_Easy"); // NOI18N
        jRadioButtonEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEasyActionPerformed(evt);
            }
        });

        buttonGroupDifficulty.add(jRadioButtonNormal);
        jRadioButtonNormal.setText("Normal");
        jRadioButtonNormal.setName("jRadioButton_Normal"); // NOI18N
        jRadioButtonNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNormalActionPerformed(evt);
            }
        });

        buttonGroupDifficulty.add(jRadioButtonHard);
        jRadioButtonHard.setText("Hard");
        jRadioButtonHard.setName("jRadioButton_Hard"); // NOI18N
        jRadioButtonHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHardActionPerformed(evt);
            }
        });

        jLabelTitleText.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        jLabelTitleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleText.setText("HANGMAN");
        jLabelTitleText.setName("jLabel_TitleText"); // NOI18N

        jButtonPreferences1.setText("...");
        jButtonPreferences1.setName("jButton_Preferences"); // NOI18N
        jButtonPreferences1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreferences1ActionPerformed(evt);
            }
        });

        buttonGroupDifficulty.add(jRadioButtonAny);
        jRadioButtonAny.setSelected(true);
        jRadioButtonAny.setText("Any");
        jRadioButtonAny.setName("jRadioButton_Any"); // NOI18N
        jRadioButtonAny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAnyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGroup(jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonPreferences1))
                    .addGroup(jPanelTitleLayout.createSequentialGroup()
                        .addGroup(jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTitleLayout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addGroup(jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelTitleLayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jButtonDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelTitleLayout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jLabelTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 225, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jRadioButtonEasy)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonNormal)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonHard)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonAny)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPreferences1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabelTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEasy)
                    .addComponent(jRadioButtonNormal)
                    .addComponent(jRadioButtonHard)
                    .addComponent(jRadioButtonAny))
                .addGap(66, 66, 66))
        );

        getContentPane().add(jPanelTitle, "cardTitle");

        jPanelDictionary.setName("cardDictionary"); // NOI18N
        jPanelDictionary.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelDictionaryComponentShown(evt);
            }
        });

        jComboBoxSelectList.setModel(new DefaultComboBoxModel(game.getListNames()));
        jComboBoxSelectList.setSelectedIndex(0);

        jComboBoxSelectList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxSelectListItemStateChanged(evt);
            }
        });
        jComboBoxSelectList.setName("jComboBox_SelectList"); // NOI18N
        jComboBoxSelectList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectListActionPerformed(evt);
            }
        });

        jTextFieldAddWord.setName("jTextField_AddWord"); // NOI18N
        jTextFieldAddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddWordActionPerformed(evt);
            }
        });
        jTextFieldAddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddWordActionPerformed(evt);
            }
        });

        jButtonAddWord.setText("Add Word");
        jButtonAddWord.setEnabled(false);
        jButtonAddWord.setName("jButton_AddWord"); // NOI18N
        jButtonAddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddWordActionPerformed(evt);
            }
        });
        jButtonAddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddWordActionPerformed(evt);
            }
        });

        jButtonRemoveWord.setText("Remove Word");
        jButtonRemoveWord.setEnabled(false);
        jButtonRemoveWord.setName("jButton_RemoveWord"); // NOI18N
        jButtonRemoveWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveWordActionPerformed(evt);
            }
        });

        jButtonDeleteList.setText("Delete List");
        jButtonDeleteList.setEnabled(false);
        jButtonDeleteList.setName("jButton_DeleteList"); // NOI18N
        jButtonDeleteList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteListActionPerformed(evt);
            }
        });

        jScrollPaneWords.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneWords.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPaneWords.setName("jScrollPane_Words"); // NOI18N

        Object item = jComboBoxSelectList.getSelectedItem();
        DefaultListModel model = new DefaultListModel();

        for(int i = 0; i < game.getAList(item.toString()).length; i++){

            model.addElement(game.getAList(item.toString())[i]);

        }
        jList1.setModel(model);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setName("jList_Words"); // NOI18N
        jScrollPaneWords.setViewportView(jList1);

        jPanelCreateNewList.setBorder(javax.swing.BorderFactory.createTitledBorder("Create New List"));
        jPanelCreateNewList.setName("jPanel_CreateNewList"); // NOI18N

        jLabelListName.setText("List Name:");
        jLabelListName.setName("jLabel_ListName"); // NOI18N

        jTextFieldAddList.setName("jTextField_AddList"); // NOI18N
        jTextFieldAddList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddListActionPerformed(evt);
            }
        });
        jTextFieldAddList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuildListActionPerformed(evt);
            }
        });

        jButtonBuildList.setText("Build List");
        jButtonBuildList.setName("jButton_BuildList"); // NOI18N
        jButtonBuildList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuildListActionPerformed(evt);
            }
        });
        jButtonBuildList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuildListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCreateNewListLayout = new javax.swing.GroupLayout(jPanelCreateNewList);
        jPanelCreateNewList.setLayout(jPanelCreateNewListLayout);
        jPanelCreateNewListLayout.setHorizontalGroup(
            jPanelCreateNewListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateNewListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelListName)
                .addGap(18, 18, 18)
                .addGroup(jPanelCreateNewListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBuildList, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jTextFieldAddList))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelCreateNewListLayout.setVerticalGroup(
            jPanelCreateNewListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateNewListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCreateNewListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelListName)
                    .addComponent(jTextFieldAddList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonBuildList)
                .addContainerGap())
        );

        jLabelHangmanDictionary.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        jLabelHangmanDictionary.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHangmanDictionary.setText("HANGMAN DICTIONARY");
        jLabelHangmanDictionary.setName("jLabel_HangmanDictionary"); // NOI18N

        jButtonPreferences3.setText("...");
        jButtonPreferences3.setName("jButton_Preferences3"); // NOI18N
        jButtonPreferences3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreferences3ActionPerformed(evt);
            }
        });

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDictionaryLayout = new javax.swing.GroupLayout(jPanelDictionary);
        jPanelDictionary.setLayout(jPanelDictionaryLayout);
        jPanelDictionaryLayout.setHorizontalGroup(
            jPanelDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDictionaryLayout.createSequentialGroup()
                .addGroup(jPanelDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDictionaryLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanelDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDictionaryLayout.createSequentialGroup()
                                .addGroup(jPanelDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPaneWords)
                                    .addComponent(jComboBoxSelectList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelDictionaryLayout.createSequentialGroup()
                                        .addComponent(jTextFieldAddWord, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAddWord))
                                    .addGroup(jPanelDictionaryLayout.createSequentialGroup()
                                        .addComponent(jButtonRemoveWord, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonDeleteList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanelDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDictionaryLayout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(jPanelCreateNewList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDictionaryLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelDictionaryLayout.createSequentialGroup()
                                .addComponent(jLabelHangmanDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 30, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDictionaryLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPreferences3)))
                .addContainerGap())
        );
        jPanelDictionaryLayout.setVerticalGroup(
            jPanelDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDictionaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPreferences3)
                .addGap(1, 1, 1)
                .addComponent(jLabelHangmanDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDictionaryLayout.createSequentialGroup()
                        .addComponent(jComboBoxSelectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAddWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAddWord))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPaneWords, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelCreateNewList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemoveWord)
                    .addComponent(jButtonDeleteList)
                    .addComponent(jButtonBack))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelDictionary, "cardDictionary");

        jPanelGame.setName("cardGame"); // NOI18N

        jPanelHangmanGraphics.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelHangmanGraphics.setName("jPanel_HangmanGraphics"); // NOI18N

        jButtonPreferences2.setText("...");
        jButtonPreferences2.setName("jButton_Preferences2"); // NOI18N
        jButtonPreferences2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreferences2ActionPerformed(evt);
            }
        });

        jLabelResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelResult.setForeground(new java.awt.Color(255, 0, 51));
        jLabelResult.setText("Congratulations!  You won!");

        jLabelScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelScore.setText("Score: 0");

        javax.swing.GroupLayout jPanelHangmanGraphicsLayout = new javax.swing.GroupLayout(jPanelHangmanGraphics);
        jPanelHangmanGraphics.setLayout(jPanelHangmanGraphicsLayout);
        jPanelHangmanGraphicsLayout.setHorizontalGroup(
            jPanelHangmanGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHangmanGraphicsLayout.createSequentialGroup()
                .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 486, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHangmanGraphicsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelScore, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPreferences2))
        );
        jPanelHangmanGraphicsLayout.setVerticalGroup(
            jPanelHangmanGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHangmanGraphicsLayout.createSequentialGroup()
                .addGroup(jPanelHangmanGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPreferences2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelAlphabet.setBorder(javax.swing.BorderFactory.createTitledBorder("Guess a Letter"));
        jPanelAlphabet.setName("jPanel_Alphabet"); // NOI18N

        jButtonA.setText("A");
        jButtonA.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonA.setName("jButton_A"); // NOI18N

        jButtonB.setText("B");
        jButtonB.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonB.setName("jButton_B"); // NOI18N

        jButtonC.setText("C");
        jButtonC.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonC.setName("jButton_C"); // NOI18N

        jButtonD.setText("D");
        jButtonD.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonD.setName("jButton_D"); // NOI18N

        jButtonE.setText("E");
        jButtonE.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonE.setName("jButton_E"); // NOI18N

        jButtonF.setText("F");
        jButtonF.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonF.setName("jButton_F"); // NOI18N

        jButtonG.setText("G");
        jButtonG.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonG.setName("jButton_G"); // NOI18N

        jButtonH.setText("H");
        jButtonH.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonH.setName("jButton_H"); // NOI18N

        jButtonI.setText("I");
        jButtonI.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonI.setName("jButton_I"); // NOI18N

        jButtonJ.setText("J");
        jButtonJ.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonJ.setName("jButton_J"); // NOI18N

        jButtonK.setText("K");
        jButtonK.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonK.setName("jButton_K"); // NOI18N

        jButtonL.setText("L");
        jButtonL.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonL.setName("jButton_L"); // NOI18N

        jButtonM.setText("M");
        jButtonM.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonM.setName("jButton_M"); // NOI18N

        jButtonN.setText("N");
        jButtonN.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonN.setName("jButton_N"); // NOI18N

        jButtonO.setText("O");
        jButtonO.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonO.setName("jButton_O"); // NOI18N

        jButtonP.setText("P");
        jButtonP.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonP.setName("jButton_P"); // NOI18N

        jButtonQ.setText("Q");
        jButtonQ.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonQ.setName("jButton_Q"); // NOI18N

        jButtonR.setText("R");
        jButtonR.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonR.setName("jButton_R"); // NOI18N

        jButtonS.setText("S");
        jButtonS.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonS.setName("jButton_S"); // NOI18N

        jButtonT.setText("T");
        jButtonT.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonT.setName("jButton_T"); // NOI18N

        jButtonU.setText("U");
        jButtonU.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonU.setName("jButton_U"); // NOI18N

        jButtonV.setText("V");
        jButtonV.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonV.setName("jButton_V"); // NOI18N

        jButtonW.setText("W");
        jButtonW.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonW.setName("jButton_W"); // NOI18N

        jButtonX.setText("X");
        jButtonX.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonX.setName("jButton_X"); // NOI18N

        jButtonY.setText("Y");
        jButtonY.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonY.setName("jButton_Y"); // NOI18N

        jButtonZ.setText("Z");
        jButtonZ.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonZ.setName("jButton_Z"); // NOI18N

        jScrollPaneWord.setBorder(null);
        jScrollPaneWord.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jLabelWord.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWord.setText("THE CURRENT WORD WILL GO HERE");
        jScrollPaneWord.setViewportView(jLabelWord);

        javax.swing.GroupLayout jPanelAlphabetLayout = new javax.swing.GroupLayout(jPanelAlphabet);
        jPanelAlphabet.setLayout(jPanelAlphabetLayout);
        jPanelAlphabetLayout.setHorizontalGroup(
            jPanelAlphabetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlphabetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlphabetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneWord, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAlphabetLayout.createSequentialGroup()
                        .addComponent(jButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAlphabetLayout.createSequentialGroup()
                        .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAlphabetLayout.setVerticalGroup(
            jPanelAlphabetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlphabetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlphabetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlphabetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPaneWord, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });
        jButtonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuess(evt);
            }
        });

        jButtonQuit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonQuit.setText("<html>Record Score and Quit</html>");
        jButtonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitActionPerformed(evt);
            }
        });

        jButtonContinue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonContinue.setText("<html>Continue Playing</html>");
        jButtonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGameLayout = new javax.swing.GroupLayout(jPanelGame);
        jPanelGame.setLayout(jPanelGameLayout);
        jPanelGameLayout.setHorizontalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHangmanGraphics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelGameLayout.createSequentialGroup()
                        .addComponent(jButtonQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelAlphabet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jButtonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelGameLayout.setVerticalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHangmanGraphics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAlphabet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonContinue)
                    .addComponent(jButtonQuit))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanelGame, "cardGame");

        jPanelLeaderboard.setName("jPanelLeaderboard"); // NOI18N
        jPanelLeaderboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPaneLeaderboard.setName("jScrollPaneLeaderboard"); // NOI18N

        jTableLeaderboard.setEnabled(false);
        jTableLeaderboard.setRowSelectionAllowed(false);
        jTableLeaderboard.getTableHeader().setReorderingAllowed(false);
        jScrollPaneLeaderboard.setViewportView(jTableLeaderboard);
        if (jTableLeaderboard.getColumnModel().getColumnCount() > 0) {
            jTableLeaderboard.getColumnModel().getColumn(0).setHeaderValue("Name");
            jTableLeaderboard.getColumnModel().getColumn(1).setHeaderValue("Score");
        }

        jPanelLeaderboard.add(jScrollPaneLeaderboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 11, 329, 485));

        jButtonLeaderboardOkay.setText("Continue");
        jButtonLeaderboardOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaderboardOkayActionPerformed(evt);
            }
        });
        jPanelLeaderboard.add(jButtonLeaderboardOkay, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, -1));

        jTextLeaderboardInputName.setToolTipText(null);

        jLabelLeaderboardInputName.setText("Name");

        jButtonLeaderboardInputConfirm.setText("Confirm");
        jButtonLeaderboardInputConfirm.setToolTipText(null);
        jButtonLeaderboardInputConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaderboardInputConfirmActionPerformed(evt);
            }
        });

        jLabelLeaderboardInputCongrats.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLeaderboardInputCongrats.setText("New high score! Enter your name!");

        javax.swing.GroupLayout jPanelLeaderboardInputLayout = new javax.swing.GroupLayout(jPanelLeaderboardInput);
        jPanelLeaderboardInput.setLayout(jPanelLeaderboardInputLayout);
        jPanelLeaderboardInputLayout.setHorizontalGroup(
            jPanelLeaderboardInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeaderboardInputLayout.createSequentialGroup()
                .addGroup(jPanelLeaderboardInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLeaderboardInputLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabelLeaderboardInputName))
                    .addGroup(jPanelLeaderboardInputLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jTextLeaderboardInputName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButtonLeaderboardInputConfirm)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLeaderboardInputLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelLeaderboardInputCongrats)
                .addGap(90, 90, 90))
        );
        jPanelLeaderboardInputLayout.setVerticalGroup(
            jPanelLeaderboardInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeaderboardInputLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabelLeaderboardInputCongrats)
                .addGap(18, 18, 18)
                .addGroup(jPanelLeaderboardInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLeaderboardInputConfirm)
                    .addGroup(jPanelLeaderboardInputLayout.createSequentialGroup()
                        .addComponent(jLabelLeaderboardInputName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextLeaderboardInputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jTextLeaderboardInputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaderboardInputConfirmActionPerformed(evt);
            }
        });

        jPanelLeaderboard.add(jPanelLeaderboardInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 11, -1, -1));

        getContentPane().add(jPanelLeaderboard, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartGameActionPerformed
        
        game.initGame();

        //sets up the word "blanks"
        jLabelWord.setText(game.getRevealedWord().replaceAll(".(?=.)", "$0    ").trim());
        
        //Hides Continue/Quit Buttons
        jButtonContinue.setEnabled(false);
        jButtonQuit.setVisible(true);
        jLabelResult.setText("");
        jLabelScore.setText("Score: "+game.getScore());
        
        //Swaps to Main Game Screen
        jPanelGame.setVisible(true);
        jPanelTitle.setVisible(false);
        resetLetters();
        setupHangmanGraphics();
        redrawBody();
    }//GEN-LAST:event_jButtonStartGameActionPerformed

    private void jButtonDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDictionaryActionPerformed
        //Swaps to Dictionary Screen
        jPanelDictionary.setVisible(true);
        jPanelTitle.setVisible(false);
    }//GEN-LAST:event_jButtonDictionaryActionPerformed

    private void jButtonPreferences1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreferences1ActionPerformed
        //Opens Preferences Dialog Box
        new HangmanPreferencesGUI(this).setVisible(true);
    }//GEN-LAST:event_jButtonPreferences1ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        //Swaps back to Title Screen (from Dictionary Screen)
        jPanelDictionary.setVisible(false);
        jPanelTitle.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinueActionPerformed
        game.newWord();

        //sets up the word "blanks"
        jLabelWord.setText(game.getRevealedWord().replaceAll(".(?=.)", "$0    ").trim());
        
        //Hides Continue/Quit Buttons
        jButtonContinue.setEnabled(false);
        jLabelResult.setText("");
        resetLetters();
        redrawBody();
    }//GEN-LAST:event_jButtonContinueActionPerformed

    private void jRadioButtonEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEasyActionPerformed
        game.setDifficulty(1);
    }//GEN-LAST:event_jRadioButtonEasyActionPerformed

    private void jRadioButtonNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNormalActionPerformed
        game.setDifficulty(2);
    }//GEN-LAST:event_jRadioButtonNormalActionPerformed

    private void jRadioButtonHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHardActionPerformed
        game.setDifficulty(3);
    }//GEN-LAST:event_jRadioButtonHardActionPerformed

    private void jButtonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitActionPerformed
        //Asks User for Name, Records Score, and Swaps back to Title Screen (from Game Screen)
        jButtonQuit.setVisible(false);
        jPanelDictionary.setVisible(false);
        jPanelGame.setVisible(false);
        jPanelTitle.setVisible(false);
        jPanelLeaderboard.setVisible(true);
        
        if(game.checkScore()){
            
            jPanelLeaderboardInput.setVisible(true);
            
        } else{
            
            jPanelLeaderboardInput.setVisible(false);
            
        }
        
    }//GEN-LAST:event_jButtonQuitActionPerformed

    private void jPanelDictionaryComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelDictionaryComponentShown
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jPanelDictionaryComponentShown

    private void jComboBoxSelectListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxSelectListItemStateChanged
        // TODO add your handling code here:
        Object item = jComboBoxSelectList.getSelectedItem();
        DefaultListModel model = new DefaultListModel();
        
        jList1.setListData(game.getAList(item.toString()));
        jList1.setSelectedIndex(0);
        
        if(item.toString().equals("easy") || item.toString().equals("medium") || item.toString().equals("hard")){
            
            jButtonAddWord.setEnabled(false);
            jButtonRemoveWord.setEnabled(false);
            jButtonDeleteList.setEnabled(false);
            
        } else{
            
            jButtonAddWord.setEnabled(true);
            jButtonRemoveWord.setEnabled(true);
            jButtonDeleteList.setEnabled(true);
            
        }
        
    }//GEN-LAST:event_jComboBoxSelectListItemStateChanged

    private void jButtonBuildListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuildListActionPerformed
        // TODO add your handling code here:
        
        if (jTextFieldAddList.getText().equals("")) return; //don't add list if empty
        
        XMLParser theParser = new XMLParser();
        theParser.writeHangmanFile(new String[0], jTextFieldAddList.getText());
        
        game.setUp();
        int listnum = jComboBoxSelectList.getSelectedIndex();
        jComboBoxSelectList.setModel(new DefaultComboBoxModel(game.getListNames()));
        jComboBoxSelectList.setSelectedIndex(listnum);
        jTextFieldAddList.setText("");
        
    }//GEN-LAST:event_jButtonBuildListActionPerformed

    private void jComboBoxSelectListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSelectListActionPerformed

    private void jButtonAddWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddWordActionPerformed
        // TODO add your handling code here:
        if (jTextFieldAddWord.getText().equals("")) return; //don't add word if empty
        if (!jButtonAddWord.isEnabled()) return; //if button is grayed out, stop (used for when pressing enter on text field)
        
        Object item = jComboBoxSelectList.getSelectedItem();
        DefaultListModel model = new DefaultListModel();
        String[] newList = new String[game.getAList(item.toString()).length + 1];
        newList[0] = item.toString();
        
        for(int i = 0; i < game.getAList(item.toString()).length; i++){
            
            model.addElement(game.getAList(item.toString())[i]);
            newList[i+1] = game.getAList(item.toString())[i];
            
        }
        
        model.addElement(jTextFieldAddWord.getText());
        newList[game.getAList(item.toString()).length] = jTextFieldAddWord.getText();
        
        System.out.println(item.toString());
        
        XMLParser theParser = new XMLParser();
        theParser.writeHangmanFile(newList, item.toString());
        
        jList1.setModel(model);
        jList1.setSelectedIndex(0);
        jTextFieldAddWord.setText("");
        game.setUp();
        
    }//GEN-LAST:event_jButtonAddWordActionPerformed

    private void jButtonRemoveWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveWordActionPerformed
        // TODO add your handling code here:
        
        Object item = jComboBoxSelectList.getSelectedItem();
        DefaultListModel model = new DefaultListModel();
        String[] newList = new String[game.getAList(item.toString()).length-1];
        newList[0] = item.toString();
        String selectedWord = jList1.getSelectedValue();
        int lengthModifier = 0;
        
        for(int i = 0; i < (game.getAList(item.toString()).length - 1); i++){
            
            if(!game.getAList(item.toString())[i].equals(selectedWord)){
                
                model.addElement(game.getAList(item.toString())[i]);
                newList[i+1-lengthModifier] = game.getAList(item.toString())[i];
            
            }else{
                
                lengthModifier++;
                
            }
            
        }
        
        XMLParser theParser = new XMLParser();
        theParser.writeHangmanFile(newList, item.toString());
        
        jList1.setModel(model);
        jList1.setSelectedIndex(0);
        game.setUp();
        
    }//GEN-LAST:event_jButtonRemoveWordActionPerformed

    private void jButtonDeleteListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteListActionPerformed
        // TODO add your handling code here:
        XMLParser theParser = new XMLParser();
        
        theParser.eraseHangmanFile(jComboBoxSelectList.getSelectedItem().toString());
        
        game.setUp();
        
        jComboBoxSelectList.setModel(new DefaultComboBoxModel(game.getListNames()));
        jComboBoxSelectList.setSelectedIndex(0);
        
        Object item = jComboBoxSelectList.getSelectedItem();
        
        jList1.setListData(game.getAList(item.toString()));
        jList1.setSelectedIndex(0);
        
        jButtonAddWord.setEnabled(false);
        jButtonRemoveWord.setEnabled(false);
        jButtonDeleteList.setEnabled(false);        
        
    }//GEN-LAST:event_jButtonDeleteListActionPerformed

    private void jTextFieldAddListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddListActionPerformed

    private void jTextFieldAddWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddWordActionPerformed

    private void jButtonPreferences3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreferences3ActionPerformed
        // TODO add your handling code here:
        new HangmanPreferencesGUI(this).setVisible(true);
    }//GEN-LAST:event_jButtonPreferences3ActionPerformed

    private void jButtonPreferences2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreferences2ActionPerformed
        // TODO add your handling code here:
        new HangmanPreferencesGUI(this).setVisible(true);
    }//GEN-LAST:event_jButtonPreferences2ActionPerformed

    private void jRadioButtonAnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAnyActionPerformed
        game.setDifficulty(0);
    }//GEN-LAST:event_jRadioButtonAnyActionPerformed

    private void jButtonLeaderboardOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaderboardOkayActionPerformed
        // TODO add your handling code here:
        jPanelLeaderboard.setVisible(false);
        jPanelTitle.setVisible(true);
    }//GEN-LAST:event_jButtonLeaderboardOkayActionPerformed

    private void jButtonLeaderboardInputConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaderboardInputConfirmActionPerformed
        if (jTextLeaderboardInputName.getText().equals("")) return; //don't do anything if text field is empty
        
        game.submitScore(jTextLeaderboardInputName.getText());
        jTableLeaderboard.setModel(new DefaultTableModel(game.getScores(),new String[]{"Name","Score"}));
        jScrollPaneLeaderboard.revalidate();
        jScrollPaneLeaderboard.repaint();
        jPanelLeaderboardInput.setVisible(false);

    }//GEN-LAST:event_jButtonLeaderboardInputConfirmActionPerformed

    //Takes the text of a button (the letter) and sends it to Hangman.java to see if user guessed a correct letter
    private void jButtonGuess(java.awt.event.ActionEvent evt) {
        if (game.isGameOver()) return; //don't let user click any letters if game over
        
        JButton button = (JButton) evt.getSource(); //gets the object (jButton) that is pressed
        String letterGuessed = evt.getActionCommand(); //gets the text of the button (the letter)
        
        //gray out the button
        button.setEnabled(false);
        
        //if correct letter guessed, green out
        if (game.takeTurn(letterGuessed)) {
            button.setOpaque(true);
            button.setBackground(Color.GREEN);
        } else redrawBody();
        
        //spaces out current word correctly o_O
        jLabelWord.setText(game.getRevealedWord().replaceAll(".(?=.)", "$0    ").trim());
        
        //when game is won/lost
        if (!game.gameStatus().equals("in progress")) {
            jLabelScore.setText("Score: "+game.getScore());
            if (game.gameStatus().equals("won")) {
                //Shows Continue/Quit Buttons
                jButtonContinue.setEnabled(true);
                jLabelResult.setText("Congratulations! You won!");
            } else {
                //Shows Quit Button Only
                jLabelResult.setText("Sorry! You lost!");
                jLabelWord.setText(game.getWord());
            }
        }
    }
    
    public void setupHangmanGraphics() {
        try {
            imageNoose = ImageIO.read(this.getClass().getClassLoader().getResource(nooseURL));
            imageHead = ImageIO.read(this.getClass().getClassLoader().getResource(headURL));
            imageBody = ImageIO.read(this.getClass().getClassLoader().getResource(bodyURL));
            imageLegs = ImageIO.read(this.getClass().getClassLoader().getResource(legsURL));
            imageArms = ImageIO.read(this.getClass().getClassLoader().getResource(armsURL));
            imageEyes = ImageIO.read(this.getClass().getClassLoader().getResource(eyesURL));
            imageMouth = ImageIO.read(this.getClass().getClassLoader().getResource(mouthURL));
        } catch (IOException e) {
        }
    }
    
    //refreshes screen for graphics
    public void redrawBody() {
        revalidate();
        repaint();
    }
    
    //enables and decolorizes all letter buttons o_O
    public void resetLetters() {
        jButtonA.setEnabled(true);
        jButtonA.setBackground(null);
        jButtonB.setEnabled(true);
        jButtonB.setBackground(null);
        jButtonC.setEnabled(true);
        jButtonC.setBackground(null);
        jButtonD.setEnabled(true);
        jButtonD.setBackground(null);
        jButtonE.setEnabled(true);
        jButtonE.setBackground(null);
        jButtonF.setEnabled(true);
        jButtonF.setBackground(null);
        jButtonG.setEnabled(true);
        jButtonG.setBackground(null);
        jButtonH.setEnabled(true);
        jButtonH.setBackground(null);
        jButtonI.setEnabled(true);
        jButtonI.setBackground(null);
        jButtonJ.setEnabled(true);
        jButtonJ.setBackground(null);
        jButtonK.setEnabled(true);
        jButtonK.setBackground(null);
        jButtonL.setEnabled(true);
        jButtonL.setBackground(null);
        jButtonM.setEnabled(true);
        jButtonM.setBackground(null);
        jButtonN.setEnabled(true);
        jButtonN.setBackground(null);
        jButtonO.setEnabled(true);
        jButtonO.setBackground(null);
        jButtonP.setEnabled(true);
        jButtonP.setBackground(null);
        jButtonQ.setEnabled(true);
        jButtonQ.setBackground(null);
        jButtonR.setEnabled(true);
        jButtonR.setBackground(null);
        jButtonS.setEnabled(true);
        jButtonS.setBackground(null);
        jButtonT.setEnabled(true);
        jButtonT.setBackground(null);
        jButtonU.setEnabled(true);
        jButtonU.setBackground(null);
        jButtonV.setEnabled(true);
        jButtonV.setBackground(null);
        jButtonW.setEnabled(true);
        jButtonW.setBackground(null);
        jButtonX.setEnabled(true);
        jButtonX.setBackground(null);
        jButtonY.setEnabled(true);
        jButtonY.setBackground(null);
        jButtonZ.setEnabled(true);
        jButtonZ.setBackground(null);
    }
    
    private static BufferedImage dye(BufferedImage image, Color color) {
        int w = image.getWidth();
        int h = image.getHeight();
        BufferedImage dyed = new BufferedImage(w,h,BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = dyed.createGraphics();
        g.drawImage(image, 0,0, null);
        g.setComposite(AlphaComposite.SrcAtop);
        g.setColor(color);
        g.fillRect(0,0,w,h);
        g.dispose();
        return dyed;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDifficulty;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonAddWord;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBuildList;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonDeleteList;
    private javax.swing.JButton jButtonDictionary;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonG;
    private javax.swing.JButton jButtonH;
    private javax.swing.JButton jButtonI;
    private javax.swing.JButton jButtonJ;
    private javax.swing.JButton jButtonK;
    private javax.swing.JButton jButtonL;
    private javax.swing.JButton jButtonLeaderboardInputConfirm;
    private javax.swing.JButton jButtonLeaderboardOkay;
    private javax.swing.JButton jButtonM;
    private javax.swing.JButton jButtonN;
    private javax.swing.JButton jButtonO;
    private javax.swing.JButton jButtonP;
    private javax.swing.JButton jButtonPreferences1;
    private javax.swing.JButton jButtonPreferences2;
    private javax.swing.JButton jButtonPreferences3;
    private javax.swing.JButton jButtonQ;
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JButton jButtonR;
    private javax.swing.JButton jButtonRemoveWord;
    private javax.swing.JButton jButtonS;
    private javax.swing.JButton jButtonStartGame;
    private javax.swing.JButton jButtonT;
    private javax.swing.JButton jButtonU;
    private javax.swing.JButton jButtonV;
    private javax.swing.JButton jButtonW;
    private javax.swing.JButton jButtonX;
    private javax.swing.JButton jButtonY;
    private javax.swing.JButton jButtonZ;
    private javax.swing.JComboBox<String> jComboBoxSelectList;
    private javax.swing.JLabel jLabelHangmanDictionary;
    private javax.swing.JLabel jLabelLeaderboardInputCongrats;
    private javax.swing.JLabel jLabelLeaderboardInputName;
    private javax.swing.JLabel jLabelListName;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelScore;
    private javax.swing.JLabel jLabelTitleText;
    private javax.swing.JLabel jLabelWord;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanelAlphabet;
    private javax.swing.JPanel jPanelCreateNewList;
    private javax.swing.JPanel jPanelDictionary;
    private javax.swing.JPanel jPanelGame;
    private javax.swing.JPanel jPanelHangmanGraphics;
    private javax.swing.JPanel jPanelLeaderboard;
    private javax.swing.JPanel jPanelLeaderboardInput;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JRadioButton jRadioButtonAny;
    private javax.swing.JRadioButton jRadioButtonEasy;
    private javax.swing.JRadioButton jRadioButtonHard;
    private javax.swing.JRadioButton jRadioButtonNormal;
    private javax.swing.JScrollPane jScrollPaneLeaderboard;
    private javax.swing.JScrollPane jScrollPaneWord;
    private javax.swing.JScrollPane jScrollPaneWords;
    private javax.swing.JTable jTableLeaderboard;
    private javax.swing.JTextField jTextFieldAddList;
    private javax.swing.JTextField jTextFieldAddWord;
    private javax.swing.JTextField jTextLeaderboardInputName;
    // End of variables declaration//GEN-END:variables
}
